# Generated by Django 3.1.4 on 2022-05-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_delete_booklists'),
        ('movies', '0002_delete_movielists'),
        ('users', '0003_auto_20220501_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books_complete',
            field=models.ManyToManyField(related_name='books_complete', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='books_dropped',
            field=models.ManyToManyField(related_name='books_dropped', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='books_progress',
            field=models.ManyToManyField(related_name='books_on_progress', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='books_waiting',
            field=models.ManyToManyField(related_name='books_waiting_list', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='movies_complete',
            field=models.ManyToManyField(related_name='movies_complete', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='movies_dropped',
            field=models.ManyToManyField(related_name='movies_dropped', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='movies_progress',
            field=models.ManyToManyField(related_name='movies_on_progress', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='movies_waiting',
            field=models.ManyToManyField(related_name='movies_waiting_list', to='movies.Movie'),
        ),
    ]
