# Generated by Django 3.1.4 on 2022-05-01 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_delete_booklists'),
        ('movies', '0002_delete_movielists'),
        ('users', '0004_auto_20220501_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='books_complete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='books_dropped',
        ),
        migrations.RemoveField(
            model_name='user',
            name='books_progress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='books_waiting',
        ),
        migrations.RemoveField(
            model_name='user',
            name='movies_complete',
        ),
        migrations.RemoveField(
            model_name='user',
            name='movies_dropped',
        ),
        migrations.RemoveField(
            model_name='user',
            name='movies_progress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='movies_waiting',
        ),
        migrations.CreateModel(
            name='MovieState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('C', 'Completado'), ('P', 'En progreso'), ('A', 'Abandonado'), ('E', 'En lista de espera')], max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('C', 'Completado'), ('P', 'En progreso'), ('A', 'Abandonado'), ('E', 'En lista de espera')], max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(through='users.BookState', to='books.Book'),
        ),
        migrations.AddField(
            model_name='user',
            name='movies',
            field=models.ManyToManyField(through='users.MovieState', to='movies.Movie'),
        ),
    ]
