# Generated by Django 3.1.4 on 2022-05-05 09:54

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220501_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='state',
            field=models.CharField(choices=[('C', 'Completado'), ('P', 'En proceso'), ('A', 'Abandonado'), ('E', 'En espera')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
