# Generated by Django 3.1.4 on 2022-05-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_booklists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklists',
            old_name='user_id',
            new_name='user',
        ),
    ]
