# Generated by Django 3.1.4 on 2022-05-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20220501_0929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookLists',
        ),
    ]
