# Generated by Django 3.1.4 on 2022-05-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_delete_booklists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='genero',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='anio',
            new_name='year',
        ),
    ]
