# Generated by Django 3.1.4 on 2022-05-01 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('autor', models.CharField(default='Anónimo', max_length=50)),
                ('anio', models.PositiveSmallIntegerField()),
                ('genero', models.CharField(choices=[('Accion', 'Acción'), ('Aventuras', 'Aventuras'), ('Ciencia Ficcion', 'Ciencia Ficción'), ('Comedia', 'Comedia'), ('Fantasia', 'Fantasía'), ('Documental', 'Documental'), ('Drama', 'Drama'), ('Musical', 'Musical'), ('Suspense', 'Suspense'), ('Terror', 'Terror')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MovieLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies_complete', models.ManyToManyField(related_name='movies_complete', to='movies.Movie')),
                ('movies_dropped', models.ManyToManyField(related_name='movies_dropped', to='movies.Movie')),
                ('movies_progress', models.ManyToManyField(related_name='movies_on_progress', to='movies.Movie')),
                ('movies_waiting', models.ManyToManyField(related_name='movies_waiting_list', to='movies.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
