# Generated by Django 3.1.4 on 2022-05-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieLists',
        ),
    ]
